[build]
publish = "site"
command = ""

[[redirects]]
  from = "/xrp-to-cash"
  to = "/xrp-to-cash-chicago.html"
  status = 301
  force = true

[[headers]]
  for = "/xrp-to-cash-chicago.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.googleapis.com *.gstatic.com; img-src 'self' data: *.googleapis.com *.gstatic.com;"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
